FROM python:3.10

USER root

# use docker build with args - passing locally set values of the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
# docker build --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ... -t metaflow .

COPY .env .env

# Create metaflow user and home directory
ENV HOME=/home/metaflow
RUN groupadd -r metaflow && useradd -r -g metaflow -d $HOME -s /sbin/nologin -c "Metaflow user" metaflow && \
    mkdir $HOME && chown -R metaflow:metaflow $HOME

# Add ec2-user as sudo user
RUN apt-get update && apt-get install -y sudo && \
    useradd -m -s /bin/bash ec2-user && \
    echo 'ec2-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    echo 'metaflow ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

ENV USERNAME=metaflow
RUN sudo chown $USERNAME:$USERNAME .env

# Create metaflow config directory and copy config file
RUN mkdir /home/.local && \
    chown -R $USERNAME:$USERNAME /home/.local && \ 
    mkdir /home/metaflow/.metaflowconfig && \
    chown -R $USERNAME:$USERNAME /home/metaflow/.metaflowconfig

COPY config.json /home/metaflow/.metaflowconfig/

# Set the Metaflow config environment variable
ENV METAFLOW_CONFIG=/home/metaflow/.metaflowconfig/config.json


# latest version of ffmpeg is not in the official repos
RUN apt-get install -y wget bzip2 && \
    apt-get install -y nasm yasm

# Update the package lists
RUN apt-get update

# Install necessary packages
RUN apt-get install -y build-essential \
    libgomp1 libavcodec-extra libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libstdc++6 \
    gfortran \
    openssl \
    gcc g++ python3-dev git ninja-build \
    ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 \
    libprotobuf-dev protobuf-compiler python3-protobuf python3-grpcio \
    python3-opencv
# Clean up the package lists to reduce the image size
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# # create volume
# VOLUME /data:20G

RUN mkdir /.metaflow && chown $USERNAME:$USERNAME /.metaflow && chmod 777 /.metaflow && mkdir -p /home/metaflow/.cache && sudo chown -R metaflow:metaflow /home/metaflow/.cache

RUN sudo -u $USERNAME pip install --upgrade setuptools pip

RUN sudo -u $USERNAME pip install black==23.3.0 pylint joblib==1.2.0 fastparquet==2023.4.0 hyperopt==0.2.7 mlflow==2.3.1 \
    metaflow>=2.8.1 scikit_learn==1.2.2 seaborn==0.12.2 xgboost==1.7.5 orjson==3.8.1 elasticsearch==8.8.0 \
    sentence_transformers==2.2.2 numpy==1.24.3 pandas==2.0.2 nltk==3.8.1 huggingface-hub==0.15.1 openai==0.27.8 \
    matplotlib==3.7.2 boto3 awscli requests wandb==0.15.5 fastcore==1.5.29 plotly==5.15.0 kaleido==0.2.1 basemap==1.3.7 \
    evidently==0.4.0 metaflow-card-html==1.0.1 tools==0.1.9 python-dotenv

ENV PATH=$PATH:$HOME/.local/bin

CMD ["python"]
