FROM python:3.10

USER root

# Environment variables
ENV HOME=/home/metaflow \
    USERNAME=metaflow \
    METAFLOW_CONFIG=/home/metaflow/.metaflowconfig/config.json

# System packages and user creation
RUN groupadd -r metaflow && useradd -r -g metaflow -d $HOME -s /sbin/nologin -c "Metaflow user" metaflow && \
    mkdir $HOME && chown -R metaflow:metaflow $HOME && \
    apt-get update && \
    apt-get install -y sudo wget bzip2 nasm yasm build-essential \
    libgomp1 libavcodec-extra libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libstdc++6 \
    gfortran \
    openssl \
    gcc g++ python3-dev git ninja-build \
    ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 \
    libprotobuf-dev protobuf-compiler python3-protobuf python3-grpcio \
    python3-opencv && \
    echo 'ec2-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    echo 'metaflow ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    rm -rf /var/lib/apt/lists/*

# Configurations
RUN mkdir -p /home/.local /home/metaflow/.metaflowconfig /.metaflow /home/metaflow/.cache && \
    chown -R $USERNAME:$USERNAME /home/.local /home/metaflow/.metaflowconfig /.metaflow /home/metaflow/.cache && \
    chmod 777 /.metaflow

# Copy the frequently changing .env file
COPY .env .env
RUN sudo chown $USERNAME:$USERNAME .env

# Copy the metaflow config
COPY config.json /home/metaflow/.metaflowconfig/

WORKDIR /opt

# Pip installations
RUN sudo -u $USERNAME pip install --upgrade setuptools pip && \
    sudo -u $USERNAME pip install black==23.3.0 pylint joblib==1.2.0 fastparquet==2023.4.0 hyperopt==0.2.7 mlflow==2.3.1 \
    metaflow>=2.8.1 scikit_learn==1.2.2 seaborn==0.12.2 xgboost==1.7.5 orjson==3.8.1 elasticsearch==8.8.0 \
    sentence_transformers==2.2.2 numpy==1.24.3 pandas==2.0.2 nltk==3.8.1 huggingface-hub==0.15.1 openai==0.27.8 \
    matplotlib==3.7.2 boto3 awscli requests wandb==0.15.5 fastcore==1.5.29 plotly==5.15.0 kaleido==0.2.1 basemap==1.3.7 \
    evidently==0.4.0 metaflow-card-html==1.0.1 tools==0.1.9 python-dotenv pathlib==1.0.1

ENV PATH=$PATH:$HOME/.local/bin

CMD ["python"]
